spring:
  application:
    name: fcat-auth
  rabbitmq:
    host: localhost
    port: 5672
    username: gjc
    password: 123456
  redis:
    host:  localhost
    database: 7
    password: 123456
    port: 6379
    timeout: 3000ms  #只难设置为ms不能为其它单位
    jedis:
      pool:
        max-active: 8  #替换了axTotal: 8
        min-idle: 1 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        testOnBorrow: true
        #max-wait: -1
    cache:
      expirationTimeMillis: 3000   #缓存过期时间 （这毫秒)
server:
  port: 8966
fcat:
  auth:
    clientId: fcat
    clientSecret: fcatSecret
    scope: server
    keystoreKey: foobar
    keystoerFilePath:  #密钥文件全路径,为空时为classpath:keystore.jks
    keystoreAliasKey: test #成密钥的密码alia
logging:
    level:
        com.xfdmao.fcat.auth: DEBUG
        com.xfdmao.fcat.api: DEBUG
    config: classpath:logback.xml
    path: /fcat/auth

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
info:
  message: authServer for other springClient must be setting in application.yml file.
