spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gjc
    password: 123456

fcat:
  auth:
    clientId: fcat
    clientSecret: fcatSecret
    scope: server
    keystoreKey: mypass    
    keystoerFilePath:  #密钥文件全路径,为空时为classpath:keystore.jks
    keystoreSelfKey: mytest ; //生成密钥的密码
logging:
    level:
        com.xfdmao.fcat.auth: DEBUG
        com.xfdmao.fcat.api: DEBUG
    config: classpath:logback.xml
    path: /fcat/auth

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
info:
  message: authServer for other springClient must be setting in application.yml file.
    