spring:
   datasource:
        name: test
        #url: jdbc:mysql://localhost:3306/fcat?useUnicode=true&characterEncoding=UTF8
        #url: jdbc:mysql://localhost:3306/cloudtest?useUnicode=true&characterEncoding=UTF8
        #url:  jdbc:mariadb://localhost:3306/cloudtest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        url:  jdbc:mysql://localhost:3306/cloudtest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        #url:  jdbc:mysql://localhost:3306/cloudtest
        username: root
        password: AAAAAAAAAA   #密码不能简单数字，否则报access deny
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        #driver-class-name: org.mariadb.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
 
  redis:
    host:  localhost
    database: 7
    password: 123456
    port: 6379
    timeout: 0ms
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 0
        max-wait: -1ms
        #max-wait: -1    
    
  rabbitmq:
    host: localhost
    port: 5672
    username: gjc
    password: 123456
        
        
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600
    
server:
    port: 8964

mybatis:
    basepackage: com.xfdmao.fcat.user.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

logging:
    level:
        tk.mybatis: DEBUG
        com.xfdmao.fcat.user: DEBUG
    config: classpath:logback.xml
    path: /fcat/user

swagger:
    basepackage: com.xfdmao.fcat.user.controller
    service:
        name: fcat-user
        description: fcat-user后端服务接口
        developer: fier