spring:
    application:
        name: fcat-user
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/cloudtest?useUnicode=true&characterEncoding=UTF8
        username: root
        password: AAAAAAAAAA
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat, wall
 #下面为连接池的补充设置，应用到上面所有数据源中
 #初始化大小，最小，最大
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
# 配置获取连接等待超时的时间
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'  #各种数据库不同SELECT 1 FROM DUAL  #oracle
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql: true;druid.stat.slowSqlMillis: 5000
    redis:
        host:  localhost
        database: 7
        password: 123456
        port: 6379
        timeout: 3000ms  #只难设置为ms不能为其它单位
        jedis:
          pool:
            max-active: 8  #替换了axTotal: 8
            min-idle: 1 # 连接池中的最小空闲连接
            max-idle: 8 # 连接池中的最大空闲连接
            max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
            testOnBorrow: true
            #max-wait: -1
        cache:
          expirationTimeMillis: 3000   #缓存过期时间 （这毫秒)
    rabbitmq:
      host: localhost
      username: gjc
      password: 123456
      connection-timeout: 3s
server:
    port: 8964

security:
    oauth2:
      client:
        client-id: xfdmao-client
        client-secret: xfdmao-secret
        scope: read,write
        auto-approve-scopes: '.*'
        grant-type: password
#    user:
#        name: admin
#        password: admin
#        role: USER
#    basic:
#      enabled: false

mybatis:
    basepackage: com.xfdmao.fcat.user.mapper
    xmlLocation: classpath:mapper/**/*.xml
    typeAliasesPackage: com.xfdmao.fcat.user.mapper


management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000

logging:
    level:
        tk.mybatis: DEBUG
        com.xfdmao.fcat.user: DEBUG
    config: classpath:logback.xml
    path: /fcat/user

swagger:
    basepackage: com.xfdmao.fcat.user.controller
    service:
        name: fcat-user
        description: fcat-user后端服务接口
        developer: F1



redis:
  timeout: 30000