from: git-dev-1.0  refresh  8890
#将原来在客户端的配置文件信息，放到配置服务器中
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gjc
    password: '{cipher}AQBcO6xQMM4VLBMm8TNNBhEJnk9aEw33pxuekHPOeYlv4qwCkcJTLI/qpLrLjztU2A2+suleeot7MvdtBHsH21VN2PJOPuubiK+SOPMV0q4F69V9UBoOUdhqCMw9hmVslRQcy5hmF610K+ozhczm10FiMHhdL5ykrWBB2WMhZxaMr9PX61mZHMKDFtVVDWRFBI9GceYLOv6m36KVt6LybZyDHpL6Lbr8OWo1bk18GFTLLC9dteCT62q8YAj3J7p1F6b20xuRm0KBdaA9ps50xX501I1w6atfqPZfNKP34zBaIuV1YuuJgCwyUVzIJDH+qHBD9mngzOIQY3SStHxnbFoiouSeWpG5eWyA6JfDBao1tJrR8bu9dCeaEmVDp64EmYI='
  security:
    user:
      name: root
      password: '{cipher}AQAr1jxC5T32qKFuTjVa0x2nLLxTGsqWuLRljpRDlbzSU+CUYjPtlA84i5E24i5Sj8gEHKleVRrVXtpK2/EwH9jK65VjHygLLenVC7MhvwQVtgRmYaFqK+siHRzIP8bru9gy8PmBmEJRTMwpQV1nJPSLaKes2o6fMGSus8sGSAp2dKHSe9xTb0t7tiynsQ6eCjTHr3B//3AwpvXlG09AIY4KpezO157B5BlXIH0aFBpp3cBTjxs/Wo97uETopofCIOKmgnLYYL7VhEkzcw4DLvXZtgzr5w2Joh8LRitdIpzWzJOfX7Bj3dp6N4VN4pOslG7WQ5zajQqVkB5nF9x512NZ0dzCS2KuXt1a0jLnlhCWHc9HTmR3cMG7+uaT0Db/2GE='    
server:
  port: 8889      

management.endpoints.web.base-path: /actuator
management:
  endpoint:
    beans:
      enabled: true
      cache:
        time-to-live: 10s #设置缓存生存时间10       
    env:
      enabled: true
    shutdown:
      enabled: true
    refresh:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        exclude: shutdown
        include: bus-refresh,beans,refresh,health,info,configprops,env,conditions,metrics,mappings #'*'
      cors:
        allowed-origins: '*' #跨域支持http://example.com  
        allowed-methods: GET,POST
#  server:
#    port: 9999  #管理端点的端口号，可以独立一应用端口号
#port: -1时禁用http端点
#    ssl:
#      enabled:  #管理端口使用HTTP,不使用HTTPS
#management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans      
#info信息返回
info:  
  app:  
    name: "@project.name@"   
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"   